language: php

php:
  - 7.0
  - 7.1
  - 7.2
  - 7.3
  - 7.4snapshot
  - nightly

matrix:
  allow_failures:
    - php: nightly
    - php: 7.4snapshot

sudo: false

before_script:
  - phpenv config-rm xdebug.ini || true
  - composer self-update
  - if [[ $TRAVIS_PHP_VERSION = nightly ]]; then export COMPOSER_FLAGS=" --ignore-platform-reqs"; fi
  - composer update $COMPOSER_FLAGS
  - composer require satooshi/php-coveralls:~2.0.0 --no-update --dev $COMPOSER_FLAGS
  - composer install --prefer-source $COMPOSER_FLAGS

script:
  - php vendor/bin/phpunit

after_script:
  - php vendor/bin/coveralls
